services:
  postgres:
    image: postgres:16
    container_name: yadro_people_db
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d people"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: yadro_people_web
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/people
      - RANDOM_DATA_API_URL=https://api.randomdatatools.ru/
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
